-- MySQL Script generated by MySQL Workbench
-- Mon May 29 04:48:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- DROP DATABASE role;--  

DROP DATABASE IF EXISTS rolejava;

CREATE DATABASE IF NOT EXISTS rolejava;

USE rolejava;

-- -----------------------------------------------------
-- Table `eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_inicio` TIMESTAMP NULL,
  `data_fim` TIMESTAMP NULL,
  `local` VARCHAR(45) NULL,
  `emoji` VARCHAR(1) NULL,
  PRIMARY KEY (`id_evento`)
);
-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`)
);
-- -----------------------------------------------------
-- Table `eventos_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_has_usuarios` (
  `eventos_id_evento` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`eventos_id_evento`, `usuarios_id_usuario`),
  CONSTRAINT `fk_eventos_has_usuarios_eventos` FOREIGN KEY (`eventos_id_evento`) REFERENCES `eventos` (`id_evento`) ON DELETE CASCADE,
  CONSTRAINT `fk_eventos_has_usuarios_usuarios1` FOREIGN KEY (`usuarios_id_usuario`) REFERENCES `usuarios` (`id_usuario`) ON DELETE CASCADE 
);
-- -----------------------------------------------------
-- Table `insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos` (
  `id_insumo` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(120) NULL,
  `eventos_id_evento` INT NOT NULL,
  PRIMARY KEY (`id_insumo`),
  CONSTRAINT `fk_insumos_eventos1` FOREIGN KEY (`eventos_id_evento`) REFERENCES `eventos` (`id_evento`) ON DELETE CASCADE
);
-- -----------------------------------------------------
-- Table `transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transacoes` (
  `id_transacao` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10, 2) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  `insumos_id_insumo` INT NOT NULL,
  PRIMARY KEY (`id_transacao`),
  CONSTRAINT `fk_transacoes_usuarios1` FOREIGN KEY (`usuarios_id_usuario`) REFERENCES `usuarios` (`id_usuario`) ON DELETE CASCADE,
  CONSTRAINT `fk_transacoes_insumos1` FOREIGN KEY (`insumos_id_insumo`) REFERENCES `insumos` (`id_insumo`) ON DELETE CASCADE
);
